# Generated by Django 2.1.5 on 2019-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataCadastro',
            field=models.DateField(default='2019-01-26'),
            preserve_default=False,
        ),
    ]
